### ISSUE TITLE
TODO :

### ISSUE THREAD

**Issue by oScape** [M6Web/qmlpack-ts#12]
Agrémenter la todo au fur et à mesure des tâches
- [ ] Mettre en place les tests :
    - [ ] Installer jest 
- [ ] Properties deep dive : 
    - [ ] Passer les properties du parent à l'enfant lors d'un import
